# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f29fe9435734df9c823ac7c9d21d9fef80081ea0264ee60ef41418d9011c2152a70b0673aeb6a223e51962491c5e5500e612978df87bda56821a759672551cab

test:
  secret_key_base: a4d96685f47c0b24d2a35117b1bb248d053790fde9fdd363b0eeedd55f3b3e8cb396c0efc4b392ed74c27e98ef6b159a2c9df3c9e80c086cc5aa7092409ce5ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
