# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf9d9b7082cb13e2f3aaab2267af53ec7e8694f7a6c265786e32ac0936f6c0944f3d36d0e49ce27ff77163a76e68abe7f52aea6dbadbc145b9addc9bf30cc106

test:
  secret_key_base: 8330bf8797e6affbc83d38035c36278baf73faff4187e52c67e50f772ea33ee4bce59405a4bc0d2b2b9ec59c120c9d6f18de654edff17e2fa8b349837861e89f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
